---
services:
  dashboard-staging:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: peevenpooberry/conserved-docking-dashboard:1.0.0
    user: "1000:1000"
    ports:
      - 8051:8050
    environment:
      - PYTHONUNBUFFERED=1
    command: "python3 -u app.py"